# syntax=docker/dockerfile:1

FROM python:3.8
COPY . /app
COPY ./requirements.txt  ./app
WORKDIR ./app
VOLUME ["/data1"]
RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
EXPOSE 8080
CMD ["uvicorn", "Main:app", "--host", "0.0.0.0", "--port", "8080"]